[package]
name = "end-portal-finder"
version = "0.1.0"
authors = ["wancat <wancat@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
